const especies = [
  {
    id: 1,
    cientifico: "Tabebuia rosea",
    comun: "Ocobo, Roble",
    calificacion: 60,
    resumen: {
      id: 1,
      general: 4,
      plantaciones: 3,
      germoplasma: 7,
      generales: 2,
      optimos: 8,
      propagacion: 3,
      silvicultura: 22,
      crecimiento: 15,
      madera: 10,
      plagas: 5,
      bibliografia: 5,
    },
  },
  {
    id: 2,
    cientifico: "Bombacopsis quinata",
    comun: "Ceiba Tolua",
    calificacion: 75,
    resumen: {
      id: 2,
      general: 4,
      plantaciones: 3,
      germoplasma: 7,
      generales: 2,
      optimos: 8,
      propagacion: 3,
      silvicultura: 22,
      crecimiento: 15,
      madera: 10,
      plagas: 5,
      bibliografia: 5,
    },
  },
  {
    id: 3,
    cientifico: "Tectona grandis",
    comun: "Teca",
    calificacion: 83,
    resumen: {
      id: 3,
      general: 4,
      plantaciones: 3,
      germoplasma: 7,
      generales: 2,
      optimos: 8,
      propagacion: 3,
      silvicultura: 22,
      crecimiento: 15,
      madera: 10,
      plagas: 5,
      bibliografia: 5,
    },
  },
];

export default especies;
